# This is a basic workflow to help you get started with Actions
name: Echo on Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "🎉 Hello from GitHub Actions! You pushed to the repo!"


